### ISSUE TITLE
Circular table

### ISSUE THREAD

**Issue by Shaische** [jeffeb3/sandify#103]
Hi, not sure if this is the correct place to post it, so I apologize in advance. After searching for many different tutorials to build a sand-ball table, I think this one is the best so far! Especially the online image generator.

My question is, would it be possible to somehow convert this to a circular table? Squares are cool, but was hoping to build a circular one. I'm not a programmer, so not sure what would need to be done, but happy to open source the mechanical design as that is my profession :) Any help appreciated!

**Comment by jeffeb3** [comment]
Sure. The Sisyphus tables are round, so you can set the machine limits to a polar machine and sandify will limit the points to inside the bounds of a circle. The harder part is the software to run the table.

Marlin, or grbl, can handle cartesian (rectangle) gcodes, and they will just move the X motor when trying to move one direction and the Y motor when trying to move the other direction. They can also handle some other popular printing geometries, like corexy and delta printers. But those are not specifically polar/circular tables.

As far as I know, the software that runs the sisyphus tables is proprietary, so you can't easily just use it. But if you were going to make your own software to do that, the theta rho format is a very good way to do it. It just assigns an absolute angle and distance from the center for each point, and by the nature of the movements, it creates very smooth arcs to connect them.

Building your own table design, and the software to run it is going to be an enormous challenge, but it will be ridiculously rewarding, and you will end up with something that others will admire, and you can enjoy for a long time. 

There are also other sand table, or kinetic machines out there. Here is one WIP, with some interesting links: https://forum.v1engineering.com/t/its-not-at-all-a-zenxy/15245

We had some ideas flowing here too: https://forum.v1engineering.com/t/polar-table-design/8747

This isn't the best place to have an ongoing conversation like this, so I am going to close this issue, but feel free to keep chatting with me/us. Or if you'd like more input and more people to share with, you can make a post at the v1engineering forums. There are a lot of smart, nice, get-it-done people there who enjoy helping create machines like this.
