### ISSUE TITLE
Rounded corners on Polygons

### ISSUE THREAD

**Issue by jeffeb3** [jeffeb3/sandify#109]
Initially requested in #57. I am documenting this here, in an effort to clean up the current issues.

We could add an option for the polygons to allow rounded corners. So if the square was originally 1 unit on each side, it might have a 0.8unit length side, and an arc with a radius of 0.1units on each corner. The fraction of the shape that would be rounded would be a parameter.

**Comment by billsey** [comment]
Similar to the depth percentage on stars. (No. of points, percentage of depth)

Bill

Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------

**Comment by bobnik** [comment]
Merged with #151.
