### ISSUE TITLE
Circular Eraser

### ISSUE THREAD

**Issue by jeffeb3** [jeffeb3/sandify#111]
I think it makes sense to have a circular eraser. I am worried that right after that, I'm going to want a polygon eraser... But for now, I think it makes sense to just have something similar to a wiper, but creates a circular pattern. 

Original issue: #65

**Comment by billsey** [comment]
Or maybe a tricordal pattern?

Bill

Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------

**Comment by jeffeb3** [comment]
I'm assuming you mean throchoidal... That would be interesting.
