### ISSUE TITLE
Imported files should be treated as a custom shape

### ISSUE THREAD

**Issue by bobnik** [jeffeb3/sandify#138]
This issue has a dependent requirement of needing to support multiple shapes, #137. Once we can draw multiple shapes, the import process could be handled from the Playlist panel.

- Support a new Shape type called FileImport (or similar) that cannot be transformed. This shape won’t appear in the Shapes drop list. Attributes are Zoom, File (presumably not editable once selected), and Aspect Ratio.
- On the Layers tab, next to “New” button, add an “Import” button.
 - When clicked, should open a File dialog. If user selects a file, it will add a new FileImport layer. They can resize and move it via the preview.
- Move “where to get .thr files” and “Note about copyrights” to “About”
- Remove Import tab.

**Comment by jeffeb3** [comment]
This is spot on. Thank you. 

I do wonder if allowing transforms, but turning them off would be awesome. Using inkscape or estlcam to create a simple path (think a simple closed shape like a nike swoosh). Then importing it, then transforming it. That would have let me do the V1 logo without any changes to the code.

That is a feature I have wanted from the beginning, but it's never been this close. I may just silently enable this, and then work on some good documentation to explain how it would work later.
