### ISSUE TITLE
Support shape caching

### ISSUE THREAD

**Issue by bobnik** [jeffeb3/sandify#139]
Calculation of vertices for a base shape, given a set of specific field values, is deterministic. We recalculate the same values every time any change is made. For simple shapes, the performance impact is negligible. For more complex shapes, like some l-systems, it can bog down the UI.

I propose we do some simple in-memory caching of shapes as they are rendered. So, you would take a calculation "hit" the first time you drew a shape, but after that, the cached version could be used. We'll have to make sure we expire shapes in the cache as needed to avoid running out of memory - I am not sure what this calculation looks like, but I am hoping we can set some sensible defaults.

**Comment by jeffeb3** [comment]
The wiper doesn't need caching. Some shapes, like the star, have some options that are pretty variable, and they don't benefit from caching.
