### ISSUE TITLE
"Wiper" shape on polar machine travelling far along the "periphery"

### ISSUE THREAD

**Issue by ratnaweera** [jeffeb3/sandify#142]
Hi all,
this is more of an observation/question than an issue. I use the wiper function on my polar table, super handy! I notice it

1. travels quite far along the "periphery",
2. doubles back
3. and then starts on the next "line".

A screenshot from the sandify preview:
![Screenshot 2020-04-29 at 11 23 32](https://user-images.githubusercontent.com/40885947/80581289-3d8bc700-8a0d-11ea-9622-b7aabf04b123.png)

I might dive into the code to try and understand. But wanted to ask first: Is this the desired behaviour?

Kind regards,
Roman

**Comment by ratnaweera** [comment]
I notice it is much less pronounced when the angle between the "wiper line" and the periphery is closer to 90°. This might just be an artefact at some (strange) angles. Nothing important, by any means. Just curious.

**Comment by bobnik** [comment]
This is actually fixed in #124 and will be in the next release (presumably soon).

**Comment by ratnaweera** [comment]
Haha, thanks. Best thing I could come up with short of actually finding where in the code this "backtracking" comes from.
I'll close this non-issue 👍
