### ISSUE TITLE
SVG export optimization

### ISSUE THREAD

**Issue by msurguy** [jeffeb3/sandify#164]
Hi! 

When using export to SVG in this tool, I see that there are a lot of numbers following the floating point, increasing the file size by a factor of 2-3:

<img width="822" alt="Screen Shot 2020-07-25 at 11 14 35 PM" src="https://user-images.githubusercontent.com/585833/88472976-ac25d700-cecd-11ea-992a-6676be481d2a.png">

I found it inefficient and unnecessary to have so many numbers after the floating point in most SVG files and would suggest to trim the numbers during export to only 2 numbers after the floating point. 

You can try using https://jakearchibald.github.io/svgomg/ tool to trim floating point numbers and confirm that there's no visual difference in files, after reducing the numbers.

I have an SVG exporter package that has this nifty function that you can use to trim numbers in SVG files:
https://github.com/msurguy/svg-file-downloader/blob/master/svg-file-downloader.js#L9

**Comment by jeffeb3** [comment]
This is a great solution. Thanks.
