### ISSUE TITLE
Mask/Limits intersection code.

### ISSUE THREAD

**Issue by jeffeb3** [jeffeb3/sandify#192]
I was playing around with this on my chromebook. I'm not sure if that matters. It is an arm processor and it was in chrome.

Running the development server on my linux laptop, but it raised an exception in the limits code.

It was pretty consistent. I would do this to create it:
 - Make the first layer the standard linear wiper. I didn't change any options.
 - Add a rectangular mask
 - Scale the mask, rotate it around a bit, things like that. 

![stacktrace](https://user-images.githubusercontent.com/1812882/104135807-78d9e600-534f-11eb-99bf-f096484af4d0.png)

![atError](https://user-images.githubusercontent.com/1812882/104135810-79727c80-534f-11eb-80e3-eb045fb6dfad.png)

I spent a few minutes trying to replicate it on my laptop (Linux, firefox, i686) and it hasn't happened.

It looks like the intersection with the box is returning one point where it should be 0 or 2. The X of the one intersection point is at 250, which is maybe a clue. I am wondering if it is a precision/floating point error. But that may be my C++ experience talking.

@bobnik, Any ideas here?

I don't plan on holding up the release at all for this.

**Comment by bobnik** [comment]
Closing this. If you see it again, save a sdf version and we'll troubleshoot.
