### ISSUE TITLE
rho greater than 1 in thr file

### ISSUE THREAD

**Issue by jeffeb3** [jeffeb3/sandify#204]
https://forum.v1engineering.com/t/sandtrails-a-polar-sand-table/16844/112?u=jeffeb3

We shouldn't allow that. The thr output probably needs to add an extra guard to keep rho > 1 from happening.

**Comment by bobnik** [comment]
We could certainly put a guard there. That said, I've seen odd cases of points being allowed outside of machine boundaries, too, and I wonder if they are related. I did not investigate at the same time, but I will keep an eye out.

**Comment by bobnik** [comment]
With polarRhoMax in the Exporter, this should no longer happen. Can re-open if this is reported again.
