### ISSUE TITLE
Add as OctoPrint plugin

### ISSUE THREAD

**Issue by Isaac4211** [jeffeb3/sandify#205]
It would be amazing to add a OctoPrint plugin that emulates the site

**Comment by jeffeb3** [comment]
We have a site already, just open it in a new tab :)

Seriously though, there would be a lot of benefits of some sand table focused plugins. The gcode viewer could be better for us. Some playlist options, or random, repeat, reverse options on a playlist. 

But none if that has to do with sandify. So I'm going to decline this issue.
