### ISSUE TITLE
Bug? in exporting pattern file

### ISSUE THREAD

**Issue by mrehorst** [jeffeb3/sandify#226]
I generated a pattern and exported it without forcing the origin, then forced origin to LR corner and exported again without making any other changes. The second version, with the origin forced to LR corner, is missing all the settings that generated the pattern:
![compare](https://user-images.githubusercontent.com/17105029/162594148-bedf8fcb-e144-468d-b786-c26635b20635.jpg)

The files are identical after the few green lines on the right.

I found that when I exported the first file, the pattern parameters were displayed. When I exported the second file, the machine parameters were displayed. I switched back to the pattern parameters display and exported a third time, and this time the pattern parameters were displayed. Is it supposed to work that way?

![compareb](https://user-images.githubusercontent.com/17105029/162594338-0c249231-1e0e-4302-a7c2-e4154cc152dd.jpg)

**Comment by jeffeb3** [comment]
>  The second version, with the origin forced to LR corner, is missing all the settings that generated the pattern:

That is a bug. Good find. I bet it is having an error with the corners forced and skipping the rest of the comments. 



> I found that when I exported the first file, the pattern parameters were displayed. When I exported the second file, the machine parameters were displayed. I switched back to the pattern parameters display and exported a third time, and this time the pattern parameters were displayed. Is it supposed to work that way?

Are you saying the tab (on the right side of sandify) determined if the settings were exported correctly or not? That should not have an effect on the export. But I will test that.

**Comment by mrehorst** [comment]
Yes, that's what is happening. If the "draw" tab is selected when you export the gcode, the pattern parameters will appear in the gcode file. If the "machine" tab is selected the parameters don't appear in the gcode file. If you select the "about" tab and export, you get no parameters, same as selecting the "machine" tab.

**Comment by jeffeb3** [comment]
Ok. Thanks for finding that. It should be easy enough to find.

**Comment by bobnik** [comment]
As of #275, Sandify no longer exports settings within gcode and thr files. Those settings can be saved as a .sdf file, which produces an exact pattern replica.
