### ISSUE TITLE
Request to add a track length comment to file exports

### ISSUE THREAD

**Issue by LarsWust** [jeffeb3/sandify#233]
Request to add a line to file exports where the track length is included.

Ex (for a gcode file):
```;  Machine type: Polar
;    Max radius (mm): 200
;    Start point: none
;    End point: none
;  Content type: machine
;  Reverse export path: false
```
would change to:
```;  Machine type: Polar
;    Max radius (mm): 200
;    Start point: none
;    End point: none
;    Track length: 2186
;  Content type: machine
;  Reverse export path: false
```
This would be useful for tables since they wont have to manually calculate the track length and could be used for time estimations etc.

**Comment by bobnik** [comment]
We decided to move pattern settings out of export files in 1.0.0, so we won't be able to support this.
