### ISSUE TITLE
When multiple layer, some line doesn't exist before the exporting but is show on the exported file

### ISSUE THREAD

**Issue by vincentbraillard** [jeffeb3/sandify#234]
Let me show you. I have done multiple layer drawing and on the preview all is ok! the lines between layer are ok:
![image](https://user-images.githubusercontent.com/56022695/180880669-38e66261-5397-4bd5-8d80-f36712925a78.png)
but once I export it and import in sandify the file generated, some line is show. it is just like when ending the layer, the ball return to the end of the preview layer and then return to the end of the drawing...
![image](https://user-images.githubusercontent.com/56022695/180881030-671a09bc-f0a6-4b37-86bc-23f0c33a6695.png)
this is the file:
[Clover Variation.thr.txt](https://github.com/jeffeb3/sandify/files/9184972/Clover.Variation.thr.txt)

Any idea???. this happened not only with ths drawing but with multiple layer

**Comment by vincentbraillard** [comment]
Someone else has the same problem?

**Comment by jeffeb3** [comment]
I am not ignoring this. I will check it out when I get a minute. I have just had a very busy couple of weeks.

**Comment by vincentbraillard** [comment]
Thanks jeff.🙏

**Comment by amatismiles** [comment]
I have a similar issue where the ball returns to the start of the fancy text layer after it completes the text (destroying the text it just made).  This line does not show in the preview, but it does show when I import the thr file back in.

**Comment by bobnik** [comment]
#275 may have fixed this. When you get a chance, please re-export and try again, thanks.

**Comment by bobnik** [comment]
Closing this issue. If you see again, please upload a .sdf file that illustrates the bug, thanks.
