### ISSUE TITLE
Feature request: Max radius presets

### ISSUE THREAD

**Issue by blakegearin** [jeffeb3/sandify#235]
Hello, I thought it might be nice to incorporate some max radius presets for the Sisyphus tables. I am aware it's just a guide, but since they come in standardized sizes there's not much reason to not set it accurately. I may be wrong, but a higher size might also increase processing time.

Unfortunately I don't know the millimeters of each table currently sold. Outer dimensions are publicly available but that's quite different than the radius the ball can reach. I'm sure their support team wouldn't mind sharing. I can ask if needed.

For those not aware, here's the documentation I'm referencing.

> Max Radius: This is the size of the table from the center to the edge of the circle. On a Sisyphus table, this is really just a guide, because the pattern will get the output normalized. Patterns designed for a 250mm table will just be scaled larger on a 1m table. Setting this to your table will help the preview be more accurate.

([docs](https://github.com/jeffeb3/sandify/wiki#machine))

**Comment by jeffeb3** [comment]
Good suggestion. The size will affect the resolution of the vertices in some cases (I think). But the end pattern will fit on any table. If you are having trouble reaching the extends of the table, there is a different number (maximum rho value, in the thr output) that can adjust that.

I won't be making presets though. For one thing, the polar output isn't only used by Sisyphus tables. For another, I don't have all the sizes of table either, and getting close is close enough. It might make sense to add the sizes in the docs or a tool tip. But again, I don't work that closely with Sisyphus, and I am not sure if I would be notified if there was a change in any of the sizes (and IMO, it doesn't matter that much anyway). 

Something that is important to me is that the size you put it will stay with that browser's local storage (it's not a tracking cookie, but it is persistent between visits). So this is an onboarding issue, and once you set it, it will be set for good.
