### ISSUE TITLE
Add new "code" layer

### ISSUE THREAD

**Issue by michaelcunningham1974** [jeffeb3/sandify#237]
It would be useful to have a new layer type called code that would provide a textbox that arbitrary code could be entered similar to the start/end code in the machine settings.

I envision this being useful to do things like pauses  between layers, changing federates, changing led settings, custom pin/io etc.

**Comment by jeffeb3** [comment]
This is several months old now, I'm not sure how I missed it. 

That would be easy enough to add. My concern is just being able to get the user to understand it. We wouldn't be able to have any kind of preview for that text, it would just be a layer that gets copy/pasted at the end. I'm not 100% sure our architecture can manage that kind of storage through to the download ATM either.

**Comment by bobnik** [comment]
Added in #302
