### ISSUE TITLE
Draw Portion being converted to int

### ISSUE THREAD

**Issue by jeffeb3** [jeffeb3/sandify#257]
https://forum.v1engineering.com/t/sandify-update-v0-2-7/34684/17?u=jeffeb3

I checked, and I can edit the value in the front end as a float (the arrows move by 1, but I can type in 99.5). But the result looks like it floors it to the lower integer.

**Comment by jeffeb3** [comment]
![5db0424830b240350c58a1c5a3c5b71ce5be700c_2_490x1000](https://user-images.githubusercontent.com/1812882/204324533-5f325dc6-e1ea-4ec4-b719-d13bf510ee37.jpeg)

**Comment by bobnik** [comment]
Fixed in #275
