### ISSUE TITLE
Export Adds Points 

### ISSUE THREAD

**Issue by jeffeb3** [jeffeb3/sandify#258]
https://forum.v1engineering.com/t/sandify-update-v0-2-7/34684/21?u=jeffeb3

[coquillage (1).zip](https://github.com/jeffeb3/sandify/files/10114483/coquillage.1.zip)

![screenshot-2022-11-29-1669735652](https://user-images.githubusercontent.com/1812882/204572443-0f72952d-137e-49b1-b559-e77a04bc0adc.png)

I don't think it has to do with the "connect to next layer" option. It seems to travel from the end of pattern 1 to the beginning of pattern 3, then back to the beginning of pattern 2. I have to have at least the first three imports enabled to see it.

**Comment by V1EngineeringInc** [comment]
This happened on my logo pattern. It added exactly one extra point. I found it odd. I thought I had maybe added a point layer, but that would have added two point, start and end, but it didn't (I don't think).

**Comment by bobnik** [comment]
#275 may have fixed this. Please try again, thanks.

**Comment by bobnik** [comment]
I'm going to go ahead and close this. Please submit another issue with a .sdf file as example if you see it again.
