### ISSUE TITLE
Our sortable dependency is being deprecated

### ISSUE THREAD

**Issue by jeffeb3** [jeffeb3/sandify#260]
https://github.com/clauderic/react-sortable-hoc

It looks like they are pusing for dnd-kit (drag and drop) instead: https://github.com/clauderic/dnd-kit

I'm not interested in tackling this while I am doing this other stuff. It should be a simplish fix then (and maybe we can add some new functionality at the same time).

**Comment by bobnik** [comment]
Fixed in #275
