### ISSUE TITLE
help with sandsara Table

### ISSUE THREAD

**Issue by PicMyPlace** [jeffeb3/sandify#263]
Hello, im a total noob in all of this, but hopefully someone here can help me :D 

I just got a beautiful sansara table and trying to create my first custom patterns with sandify. Unfortunately my Sandsara doesnt seem to recognize any of the files that i put on the internal Micro SD Card.  Also their support is super slow, all i got from them so far is this posting: https://www.indiegogo.com/projects/sandsara/x/27126592#/updates/23

there they say that sandsara supports .thr files, and in the manual it says that i only have to put them on the sd card, nothing else. in the post above it says that for mobile apps they use .bin files. i spend the whole day exporting with sandify and trying to convert .thr files to .bin files because the standard pattenrns that already were on the sd card are all in .bin  but i have no idea how to convert them^^

please help :D   and thanks so much for your time and knowledge^!!

nico

**Comment by jeffeb3** [comment]
I do not know anything about the sandara tables, or their firmware.

From the post you shared, it looks like they support sandify generated thr files. But it doesn't have a good description on how to get them to the table.

Are there other .thr files somewhere on the microsd card? 

Does the app have a way to import a file and push it to the table?

I'm happy to keep thinking through this with you, just keep commenting here with ideas and data. But I am going to close the issue, because it isn't an issue with sandify. We can reopen if it we decide there is something sandify can do to fix it.

**Comment by PicMyPlace** [comment]
Hey Jeff,

 

wow thanks so much for your super fast reply 😃   yes totally understandable, close the issue no problem. 

 

This is the full content of the SD Card that came with the Sandsara:

https://we.tl/t-40BmpoH3U4

 

There are only .bin files and a playlist file.

 

Apart from that I only have the Support thread that I already shared in the github issue, there it says to use sandify (which I love btw), the only thing that I cant get to work is putting the cool patterns correctly on the sd card apparently….  

 

Thanks so much for your time! 

 

Nico 

 



______________________
Nicolas Oberlik 
PicMyPlace GmbH
Geschäftsführer
***@***.*** ***@***.***> 
www.picmyplace.com <http://www.picmyplace.com> 
+43 676 5623320
 
PicMyPlace GmbH
Eßlinggasse 2/IV Mezzanin
1010 Wien

**Comment by jeffeb3** [comment]
I can't open the we transfer. It looks like it just drops me at the landing page. Not a big deal though. I trust your description.

The indigogo site says the .bin are a binary representation of the txt format, which is x, y, not theta, rho. So I would try just putting the thr files on the sdcard. Ignoring the .bin for now.

I would also try a simpler, smaller thr file. Something like this:

test.thr:
```
0.0 0.0
628.0 1.0
```
That should take about 100 rotations to go from the center to the rim, in a big spiral.

The other thing I would try is to have a .thr file on your smart phone, and see if there is a menu option for importing a track. The sisyphus app has that option in the settings. If you are having trouble getting your test or specific .thr file to the phone, you can use sandify on the phone to generate some test .thr file and use that. From their description, it sounds like the app converts the files to .bin when copying them to the table. IDK if it only supports .txt formats, or .thr also. For that reason, I would try the .thr on the microsd first.

Sandify can't make the .txt files or the .bin files for the sandsara tables. I assume it would be easy to add. But if it already supports .thr, then that would be a lot better for everyone.

**Comment by jeffeb3** [comment]
There is also a kickstarter: https://www.kickstarter.com/projects/edcano/sandsara/comments Some of those comments might be helpful. There is one there about the playlist.playlist file. IDK if that helps or not.

**Comment by PicMyPlace** [comment]
Ok cool! Thanks so much for your input!I will keep trying tomorrow and get back to you if i get any results :DThanks and take care! Nico 
-------- Ursprüngliche Nachricht --------Von: Jeff Eberl ***@***.***> Datum: 19.01.23  19:57  (GMT+01:00) An: jeffeb3/sandify ***@***.***> Cc: PicMyPlace ***@***.***>, Author ***@***.***> Betreff: Re: [jeffeb3/sandify] help with sandsara Table (Issue #263) 
There is also a kickstarter: https://www.kickstarter.com/projects/edcano/sandsara/comments Some of those comments might be helpful. There is one there about the playlist.playlist file. IDK if that helps or not.

**Comment by jeffeb3** [comment]
That is awesome. Glad you figured it out.

I don't know the mechanics of your table. It sounds like the theta is reversed. If the theta motor is independent enough and a stepper motor, you can reverse its direction by flipping the plug. For a software solution, you would have to reverse the theta on every line in the file. You could do that with a script that read in each line and reversed the sign. I won't be doing that in sandify. 

Ideally, this is a problem you would ask the manufacturer about. They could suggest a wiring solution, or add a configuration parameter in their software to flip the theta when reading thr files.

**Comment by PicMyPlace** [comment]
Hey Jeff,

 

alright got it 😊 just wanted to make sure that there is no option within sandify to give out “reverse” code or thr files.

 

I will write the manufacturer and see what they say 

 

Thanks for your help! 

 

Nico 

 



______________________
Nicolas Oberlik 
PicMyPlace GmbH
Geschäftsführer
***@***.*** ***@***.***> 
www.picmyplace.com <http://www.picmyplace.com> 
+43 676 5623320
 
PicMyPlace GmbH
Eßlinggasse 2/IV Mezzanin
1010 Wien

**Comment by Leopere** [comment]
can someone just upload their paths I feel like just uploading these things directly to the SD card is better than worrying about the condition of the app itself.
