### ISSUE TITLE
Feature request: Save and Open local files

### ISSUE THREAD

**Issue by kaushikbm** [jeffeb3/sandify#269]
All the layers are in the browser. One can't get it back later once the browser is closed.
It will be great if one can save a file into their local drive and later retrieve it for editing and generating the GCODE.

**Comment by vincentbraillard** [comment]
Yes that can be a helpfull function +1

**Comment by Belott** [comment]
Yes, that would really, really be helpfull! +2 :-)

**Comment by bobnik** [comment]
Added in #275
