### ISSUE TITLE
Preview render missing when width is 992px

### ISSUE THREAD

**Issue by aaronse** [jeffeb3/sandify#276]
Neat project, nice update!   Noticed preview render is not displayed when width is 992px.  Consider checking out responsive layout breakpoint logic.  Cheers!

**Comment by bobnik** [comment]
Yes, it's all built around responsive breakpoint logic. Seems we're off by a pixel point though lol. Only 992px exactly causes this issue - good catch. We'll fix.

**Comment by aaronse** [comment]
Only noticed because I like how your project is looking as was playing around to see what your responsive layouts look like :-) 
Thoughts on https://github.com/jeffeb3/sandify/pull/277 ?

**Comment by aaronse** [comment]
Built and verified fix... 

![image](https://github.com/jeffeb3/sandify/assets/16479976/f6fabb38-0c8e-457b-bbf0-deb600bffc50)

**Comment by bobnik** [comment]
Fixed by #277
