### ISSUE TITLE
crash/infinite loop with effects

### ISSUE THREAD

**Issue by luft2** [jeffeb3/sandify#283]
I'm seeing a lot of crashes when trying to create a wiper pattern.

Steps to reproduce:
1. Open sandify.org (clean site data beforehand)
2. Add new wiper layer
3. Set angle to 90° (also happens with other multiples of 90)
4. Increase size to 8.
5. Add warp effect (also works with fisheye and noise).
6. Browser tab becomes unresponsive/crashes

**Comment by jeffeb3** [comment]
Issue confirmed. Thanks for reporting it.
