### ISSUE TITLE
Error "e is undefined" when open SDF

### ISSUE THREAD

**Issue by Belott** [jeffeb3/sandify#298]
I imported the file _LimitMitReserve.gcode into Sandify and then saved it as _LimitMitReserve.SDF. 
When I then try to open the SDF file via File/open, the error message "**e is undefined**" appears.

I was able to reproduce this behavior several times with different files.
Sandifiy v1.0.0 online
(I gave the example files the extension *.txt so that I could upload them to GitHub.)

[_LimitMitReserve_GCODE.txt](https://github.com/user-attachments/files/16829517/_LimitMitReserve_GCODE.txt)
[_LimitMitReserve_SDF.txt](https://github.com/user-attachments/files/16829518/_LimitMitReserve_SDF.txt)

**Comment by jeffeb3** [comment]
I was able to import this in `master`. I will be releasing a new version soon (v1.1.0). When that comes out, you should be able to import either the gcode or sdf.

If that isn't fixed, then please re-open.
