### ISSUE TITLE
gcode files missing feed rate

### ISSUE THREAD

**Issue by diablex2** [jeffeb3/sandify#310]
I use octoprint and BetterGrbl for my DIY sand table. After not using it for a while I wanted to give it a try. I uploaded existing gcode file and had error GRBL 22 saying feed rate..... 
I made a new gcode via sandify and saw that there is no feed rate in the gcode file. 
Something changed... Or octoprint now looking for feedrate in the gcode. 
Any update to sandify for feed rate please?

**Comment by jeffeb3** [comment]
Feed rate was never in the gcode. I add it to the starting gcode in the export dialog. Marlin and grbl will keep the previously set feedrate, so something like this will work (units are mm/min):

```
G1 F1000
```

All G1 commands after that will be at 1000mm/min or 16mm/sec.
