### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by jeffeb3** [jeffeb3/sandify#34]
We should have tests. We should probably be doing test driven development.

**Comment by Allted** [comment]
As in I should start running some of them?....My bad, I am ready now at least until the big laser gets here.

**Comment by jeffeb3** [comment]
I was meaning unit tests, or software tests. Machine tests would only help to motivate the crew.

**Comment by jeffeb3** [comment]
There are some logical tests. We can always use more, but I am not going to do TDD. Closing.
