### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by jeffeb3** [jeffeb3/sandify#35]
The layout isn't great. The canvas is a static size, and the machine settings don't look like they fit, and the GCode button is hidden, with no indication that there's anything down there.

**Comment by billsey** [comment]
Visualize running this on a phone or tablet.

**Comment by jeffeb3** [comment]
Yeah, mobile is a whole other animal. I don't want to even think about running this on your phone. If someone has some experience with that, or wants to learn how to do that, fine, but I have no desire to try to make things work on a desktop and a phone, and the desktop makes a lot more sense.
