### ISSUE TITLE
Dynamic or custom shapes

### ISSUE THREAD

**Issue by jeffeb3** [jeffeb3/sandify#39]
Here's a code snippet that I added to Transform.js to create a polygon of arbitrary number of sides.

```
    var poly_points = []
    var numsides = 8
    var angle = 360.0 / numsides
    var poly_scale = 1.0
    for (var i=0; i&lt;numsides; i++) {
          var radians = angle * Math.PI / 180.0
      poly_points.push(Vertex(poly_scale * (i + 1) * Math.cos(radians * i), poly_scale * (i + 1) * Math.sin(radians * i)))
    }
```

Jeff, it’s really a special case for when you are working with a regular polygon. The turtle stuff will be much more useful for non-regular shapes (conic sections, hearts and eggs, fractals). It could easily replace the code that’s in there for the triangle and square. But then it might make sense to just do them all with turtles…

How about we do two types of regular polygons, the one I’m playing with and another that alternates between ‘in’ and ‘out’ vertices, that would allow for multi-pointed stars. Leave turtle for the odd shapes.

From:
https://www.vicious1.com/forum/topic/does-this-count-as-a-build/page/8/#post-38887

**Comment by jeffeb3** [comment]
I know that squares and triangles can be made with turtle, and that's perfectly fine. I have promised myself that I will get the turtle editor working before I do any more changes to the shapes. But, I also would like some sort of "gateway editing" where someone can design their own pattern without typing anything on the keyboard. Something just to get someone hooked. As a different mode, there is the turtle editor, which will allow much finer control of the patterns, and creativity in new ways. James and I came to that vision a while ago, of having turtle and an online editor being the path between clicking on shapes and writing javascript.

I would also like People Who Know What They Are Doing to contribute new, interesting input modes. You will be the guinea pig for that, it seems. Your dynamic shapes should either be merged in with the existing shapes (on that same tab) or brought it as a completely different tab. The spin and grow stuff is currently intricately linked with the current shapes.

**Comment by billsey** [comment]
![sandifysquare](https://user-images.githubusercontent.com/5881912/28427881-609cbb88-6d2c-11e7-8e7d-3b7b43bf590b.jpg)
In regards to the 'Growing Thing', as you can see here there's a jump in the start of the left side for each rotation instead of a smaller movement on each side. My pull is from the origin/master. My code currently shows the same results, except I am rotating center to east instead of center to northwest.

    var poly_points = []
	var num_sides = 4
    var poly_scale = 1.0
    for (var i=0; i<num_sides; i++) {
      angle = Math.PI * 2.0 / num_sides * i
      poly_points.push(Vertex(poly_scale * Math.cos(angle), poly_scale * Math.sin(angle)))
    }

**Comment by jeffeb3** [comment]
That's definitely not master. Master is yellow now. https://jeffeb3.github.io/sandify/

You probably need to merge in the more recent changes of master into your branch.

**Comment by jeffeb3** [comment]
w.r.t. dynamic shapes. If you want, I can make a dynamic shape, based on your N sided polygon, and then you can see how I did that and then create the N sided start. WDYT?

**Comment by billsey** [comment]
Weird, when I sync or pull it shows nothing newer than 7/4.

Ah, figured it out... I'd somehow created a copy in my github page that I was syncing to, instead of syncing to the real thing. Now it complains about missing the react stuff. No 'redux' or 'react-redux'.

**Comment by billsey** [comment]
Just had to install those two packages... It is looking correct now, here's the 13 sided example:
![sandify13](https://user-images.githubusercontent.com/5881912/28431057-b20a0556-6d37-11e7-9255-6d70b0944714.jpg)

**Comment by jeffeb3** [comment]
Very cool. Can you fork and push that code?

**Comment by jeffeb3** [comment]
Also, anytime the package.json adds a new dep, you'll have to run `npm install` from the toplevel. There will be a 'victor' package coming very soon.

**Comment by billsey** [comment]
Think I've got it... Created a branch with the code and committed it. Let me know what I've screwed up. :)

**Comment by jeffeb3** [comment]
A commmit is just a local thing. You have to push it too. You probably can't push to this repo though, you'll have to fork it.

**Comment by billsey** [comment]
Yep, I can't push... I fork from the github interface like I did accidentally before (clone repository)?

**Comment by jeffeb3** [comment]
Yeah, you'll fork (through the web interface), then change your origin (on your machine), then push (also on your machine).

**Comment by billsey** [comment]
OK, I think I've got it... https://github.com/billsey/sandify.git should have the latest. I'm still not sure how to pull the sidesValue variable into ShapeList, perhaps you can enlighten me?

**Comment by jeffeb3** [comment]
Got it. PR #40
