### ISSUE TITLE
Turtle scaling

### ISSUE THREAD

**Issue by barry99705** [jeffeb3/sandify#48]
Hey guys, turtle won't scale the design big enough for my table.  All I can make is a little spiral maybe 6" across.
Oh, table is X max = 1280, Y max = 2060.

**Comment by jeffeb3** [comment]
Sorry Barry, I saw this, and was going to respond when I got back to my computer, and I forgot.

I agree that it should at least be scalable to larger areas. I don't really like the slider bars, so maybe I'll just replace them with numbers like the shapes use. Then there will be no upper limits.

**Comment by jeffeb3** [comment]
Sorry Sorry Barry, I'm going to just remove the turtle stuff for now.
