### ISSUE TITLE
Sandify Webpage issue

### ISSUE THREAD

**Issue by Mahelumi** [jeffeb3/sandify#54]
Web page loaded incompletely and cannot able to design. Kindly rectify it

**Comment by jeffeb3** [comment]
I saw this bug, and I was going to complain about the lack of detail, but then I tried the page myself, and sure enough, it's totally messed up. No one has pushed a change in months, so my only thought is that one of the dependencies changed. I will look at it as soon as I can, but man, I don't know what happened.

**Comment by Mahelumi** [comment]
Thanks for the reply. We are about to test our sand table . So kindly fix this bug ASAP.

**Comment by Mahelumi** [comment]
Hey ! Its working! Thanks a lot jeff for the quick fix.
