### ISSUE TITLE
Store parameters in output

### ISSUE THREAD

**Issue by jeffeb3** [jeffeb3/sandify#59]
Mark (mrehorst) suggested I save the parameters that created the pattern in the gcode file. This is a great idea, and I would like to do that.

**Comment by mrehorst** [comment]
Thanks for adding the ability to name the output file!  If you could also save that name at the start and/or end of the file that would also be very useful.

**Comment by jeffeb3** [comment]
I have this in master, and I'll be deploying shortly.
