### ISSUE TITLE
Double line text font

### ISSUE THREAD

**Issue by billsey** [jeffeb3/sandify#68]
Instead of sleeping I've been thinking of the variations needed to the primitives we are using for the single lined font we're currently using. For instance to generate the outline for a font like this:
![dlfont](https://user-images.githubusercontent.com/5881912/50469660-3d377380-0962-11e9-9bf7-5c59deaa199d.png)
We might need to create and place curves that aren't in 90° increments, such as at the top left of the V, where the serifs require different curves. I suggest that replacing the current 'bulge direction' with a number between -360 and 360 to draw circular (modified by the font scale itself, so almost all will actually be ovals) curves the indicated number of degrees (<0 for counter clockwise, 0 for straight line and >0 for clockwise) from the current position to the ending coordinates. We'd have to have a mechanism to track the starting angle in degrees from vertical as well, using that to give the direction we're curving from.

**Comment by jeffeb3** [comment]
I think there are two good options for this. 

1) find a way outside of the javascript to encode this stuff. This font can be described pretty well with just a ton of line segments, which is already supported.
2) Use the gcode format for an arc, which is either clockwise or counterclockwise (G2, or G3), with a circle center, and a final coordinate. This is probably close the the most complete and compact way of describing arc segments.

**Comment by bobnik** [comment]
#217 implements a version of this.
