### ISSUE TITLE
More text characters

### ISSUE THREAD

**Issue by jeffeb3** [jeffeb3/sandify#70]
lowercase, international currency symbols. more punctuation. More fonts.

**Comment by jeffeb3** [comment]
Thanks. It sounds like your machine has one axis going in the wrong direction. Is it a rectangular machine or a polar machine?

**Comment by jaygrovr** [comment]
Core xy


Sent from Yahoo Mail for iPhone


On Thursday, January 24, 2019, 6:56 PM, Jeff Eberl <notifications@github.com> wrote:


Thanks. It sounds like your machine has one axis going in the wrong direction. Is it a rectangular machine or a polar machine?

**Comment by jeffeb3** [comment]
Are you able to home it? It sounds like one of your motors is inverted.

**Comment by jaygrovr** [comment]
It all works fine.. I guess one may be running reversed.. it was tricky getting the corexy stuff running.. so maybe in all those settings it went wonky.
Jason


Sent from Yahoo Mail for iPhone


On Thursday, January 24, 2019, 7:34 PM, Jeff Eberl <notifications@github.com> wrote:


Are you able to home it? It sounds like one of your motors is inverted.

**Comment by jeffeb3** [comment]
The X and Y should follow the right hand rule. On mine +x is to the right from me and +y is away from me. You might have one of the homing directions inverted as well as one of the motors. If flipping a motor doesn't work, then the motors might be switched.

The perfectionist in me wants to fix your machine :). But the engineer in me wants to add an option to flip Y or X in the machine settings (not just the text). I'm just not sure how often it is for people to have a reversed machine.

If you want to debug it, you could make a post in v1engineering.com forums and I can help you figure it out.

**Comment by jaygrovr** [comment]
I’ll fix it on my end.. makes everything easier to visualize and make content for.Thanks
Great work.
Jason


Sent from Yahoo Mail for iPhone


On Thursday, January 24, 2019, 8:35 PM, Jeff Eberl <notifications@github.com> wrote:


The X and Y should follow the right hand rule. On mine +x is to the right from me and +y is away from me. You might have one of the homing directions inverted as well as one of the motors. If flipping a motor doesn't work, then the motors might be switched.

The perfectionist in me wants to fix your machine :). But the engineer in me wants to add an option to flip Y or X in the machine settings (not just the text). I'm just not sure how often it is for people to have a reversed machine.

If you want to debug it, you could make a post in v1engineering.com forums and I can help you figure it out.

**Comment by billsey** [comment]
I've got a few more characters ready to test. Pound, Euro, Ruble, exclamation point, etc.

**Comment by jeffeb3** [comment]
Bill, feel free to push it to another branch, and I can just check it out, and copy/paste it into something to get it merged. But don't worry about it if you can't. I am going to close this issue for now.
