### ISSUE TITLE
Support vector of vertices.

### ISSUE THREAD

**Issue by jeffeb3** [jeffeb3/sandify#71]
The text is especially bothering me. I think the whole sentence needs to be treated as one object, so that growing and scaling don't mess with the shape of any single letter.

If the vertices computed were actually arrays of vertices, then we could assign each array a proportional grow/spin and not grow or spin inside the vertices of a particular array. This would let us avoid scaling letters like 'B' while drawing the B or even avoid drawing the entire sentence "FREE BEER".

**Comment by billsey** [comment]
Yeah, it's currently spinning around the bottom center of the text, though I believe it'll actually be readable since the last draw always overwrites at least part of the previous.
![freebeer](https://user-images.githubusercontent.com/5881912/50624316-eab30580-0ed3-11e9-8de8-220a41ca1f0e.png)

**Comment by jeffeb3** [comment]
The latest version has this fixed. There is a smear vs. keep intact setting on the transforms.
