### ISSUE TITLE
Rotation direction and reversal

### ISSUE THREAD

**Issue by Mcv888** [jeffeb3/sandify#72]
It would be great if the direction of rotation could be specified, but even better if the direction could be reversed during the track.  I've seen some sisyphus patterns that employ this technique and they look great.  Maybe have an additional field with number of reversals specified?
![image](https://user-images.githubusercontent.com/47325898/52215591-f8083a80-2859-11e9-9357-1f3141378e84.jpeg)

**Comment by jeffeb3** [comment]
Oh. That is cool.

**Comment by jeffeb3** [comment]
I'm working on this, and I'll have the reversals working shortly. I just noticed you also asked for the rotation direction. That's currently possible by making the spin amount negative. I'm guessing that's not intuitive enough to be obvious, so I'm thinking about adding a button. I'm not sure yet if I want that button.

**Comment by Mcv888** [comment]
Maybe amend the descriptive note to something like “spins the input shape a little bit for each copy (positive numbers spin clockwise, negatives counterclockwise)”

**Comment by jeffeb3** [comment]
![screenshot-2019-02-23-1550963217](https://user-images.githubusercontent.com/1812882/53292947-6456c980-3788-11e9-9eab-87d8947b4e03.png)

This was a great idea. Thanks. I think it will look great in the sand. I added a small not that the spin step can be negative. Hopefully that helps.
