### ISSUE TITLE
Hitting Enter Reloads Page

### ISSUE THREAD

**Issue by jexoteric** [jeffeb3/sandify#74]
When entering in numbers to any of the fields, and by habit hitting enter, the page reloads erasing all current inputs for everything except the machine size fields.

Using Firefox 65.0.1

**Comment by jeffeb3** [comment]
Agreed. This shouldn't happen. I'm sure I can disable it.

**Comment by jexoteric** [comment]
More detail: The modifier number fields under Loops, Grow, & Spin exhibit this behavior, but the fields for Track Size, Track Length, & Grow Step do not do this. 

Also duplicated on a different computer running Chrome.

**Comment by jeffeb3** [comment]
I think I've fixed this. If not, then let me know and let me know which browser and OS you're using so I can try to replicate it.

**Comment by jexoteric** [comment]
This does indeed appear to be fixed. Thank you!
