### ISSUE TITLE
Hamburger Menu Icon

### ISSUE THREAD

**Issue by jexoteric** [jeffeb3/sandify#75]
A quick UI improvement would be to add chevrons to each box bar when it is collapsed to give the user a hint that it expands down. A second option that may be easier to implement would be the horizontal lines used to show menus on mobile UIs.

![image](https://user-images.githubusercontent.com/2405436/53061351-176eac80-3483-11e9-8d2d-1dd80874fd8f.png)

**Comment by jeffeb3** [comment]
I will see what React Bootstrap can do. I need to find something I like. I think it is a little tricky.

**Comment by jeffeb3** [comment]
I thought about this some more, and the fact that it expands isn't as important as the fact that they are buttons. When they click on them, they will expand, and if it's not expanded, then it won't affect the pattern.

The one exception is the machine settings. I can't remember why I though I should hide the settings on the second click. I might rethink that.

**Comment by jexoteric** [comment]
Other than experimenting, how does a new users know easily which options are active and having an effect? I see the intent is anything that is "open"/expanded is active, but it can also just appear that anything open has a blue button (which is not clear that it means it is active). 

The chevrons or menu icons would help indicate that these are indeed buttons and can be clicked for options based on commonality with current web and mobile apps.

**Comment by jeffeb3** [comment]
When you click on the Circle button, the drawing changes to a circle and the preview shows a circle. That's the kind of reinforcement I want. What's wrong with learning through experimenting?

I imagine the hurdle is just convincing people to click on the button, or to start experimenting.

**Comment by jeffeb3** [comment]
The UI has changed enough that I don't think this applies is 0.2.0. I am closing, but feel free to comment if you don't think this has been addressed well enough.
