### ISSUE TITLE
bug in wipe pattern generation

### ISSUE THREAD

**Issue by mrehorst** [jeffeb3/sandify#80]
I found a minor bug...

If you set the angle to 0, on the graphic display it shows "distance: NaN"

Inside the gcode file that is written, you'll find this:

; Created by Sandify
; 
;   https://jeffeb3.github.io/sandify/
; 
;   Sandify Version: 0.1.3
; 
;   Machine Type: Rectangular
;     MinX: 5 MaxX: 710 MinY: 5 MaxY: 1600
;   Content Type: Wiper
;     Wiper Angle: 0
;     Wiper Size: 7
;   Path Reversed: true
; 
; filename: 'wipe0'

; BEGIN PRE
G28 Y
G28 X
G01 F60000; END PRE
G01 X710.000 Y5.000
G01 XNaN Y5.000
G01 X710.000 Y5.000
G01 X710.000 Y1144.286
G01 X710.000 Y1600.000

I searched the output file and that's the only instance of "NaN".

**Comment by jeffeb3** [comment]
Thanks. Fixed in #81
